import { notFound, redirect } from "next/navigation";

import { getCurrentUser } from "../../../../lib/auth";
import { prisma } from "../../../../lib/prisma";

import CreateTaskForm from "../../../../components/create-task-form";

type Props = {
  params: Promise<{
      id: string;
        }>;
        };

        export default async function ProjectPage({
          params,
          }: Props) {
            const user = await getCurrentUser();

              if (!user) {
                  redirect("/login");
                    }

                      const { id } = await params;

                        const project = await prisma.project.findFirst({
                            where: {
                                  id,
                                        userId: user.id,
                                            },
                                                include: {
                                                      tasks: {
                                                              orderBy: {
                                                                        createdAt: "desc",
                                                                                },
                                                                                      },
                                                                                          },
                                                                                            });

                                                                                              if (!project) {
                                                                                                  notFound();
                                                                                                    }

                                                                                                      return (
                                                                                                          <main className="min-h-screen bg-gray-50">
                                                                                                                <div className="mx-auto max-w-4xl space-y-8 px-6 py-10">
                                                                                                                        <div>
                                                                                                                                  <p className="text-sm text-gray-500">
                                                                                                                                              Project
                                                                                                                                                        </p>

                                                                                                                                                                  <h1 className="text-3xl font-bold">
                                                                                                                                                                              {project.name}
                                                                                                                                                                                        </h1>
                                                                                                                                                                                                </div>

                                                                                                                                                                                                        <section className="rounded-xl border bg-white p-6">
                                                                                                                                                                                                                  <h2 className="mb-4 text-xl font-semibold">
                                                                                                                                                                                                                              Create Task
                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                  <CreateTaskForm
                                                                                                                                                                                                                                                              projectId={project.id}
                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                        <section>
                                                                                                                                                                                                                                                                                                  <h2 className="mb-4 text-xl font-semibold">
                                                                                                                                                                                                                                                                                                              Tasks
                                                                                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                                                                                  <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                              {project.tasks.map((task) => (
                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                            key={task.id}
                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-lg border bg-white p-4"
                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      task.completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "text-gray-400 line-through"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {task.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {task.completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "Done"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "Todo"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }